name: ${project.name}
version: ${project.version}
main: com.andavin.images.Images
authors: [ 'Andavin' ]
description: ${project.description}
website: ${project.url}
softdepend:
  - ProtocolLib
api-version: '1.20'
folia-supported: true
commands:
  image:
    description: 'Manage custom images.'
    usage: /<command> <create|delete|list|upload>
    aliases: [ img ]
permissions:
  images.*:
    description: Gives access to all image commands.
    children:
      images.command.*: true
  images.command.manage:
    default: op
  images.command.create:
    default: true
  images.command.delete:
    default: true
  images.command.delete.file:
    default: true
  images.command.delete.near:
    default: true
  images.command.upload:
    default: true